version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  unit and integration test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: |
            # pytest would be a dep in requirements.txt adfdf
            pytest
          name: Test
      - store_artifacts:
          path: htmlcov

  UI test:
    executor: python/default
    steps:
      - checkout
      #- python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            # pytest would be a dep in requirements.txt adfdf
            pytest
          name: Test

workflows:
  main:
    jobs:
      - unit and integration test